name: mold_app
description: "Mold Management APP"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^14.8.1
  shared_preferences: ^2.3.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  flutter_image_compress: ^2.3.0
  intl: ^0.20.2
  pull_to_refresh_flutter3: ^2.0.2
  fluttertoast: ^8.2.10
  share_plus: ^10.1.4
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0
  sentry_flutter: ^8.12.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.0
  build_runner: ^2.4.14
  freezed: ^2.5.7
  riverpod_generator: ^2.6.2

flutter:
  uses-material-design: true
